#!/bin/sh
# SPDX-FileCopyrightText: 2026 The freelance-persona_theme Project Contributors
#
# SPDX-License-Identifier: MIT

if ! command -v betterleaks >/dev/null 2>&1; then
  echo "🛑 HALT: 'betterleaks' command not found in your PATH!"
  exit 1
fi

betterleaks protect --staged
