// SPDX-FileCopyrightText: 2026 The freelance-persona_theme Project Contributors
//
// SPDX-License-Identifier: MIT

import { defineConfig, presetUno, presetAttributify, presetIcons, transformerDirectives, transformerVariantGroup } from 'unocss';

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      collections: {
        bi: () => import('@iconify-json/bi'),
        academicons: () => import('@iconify-json/academicons'),
      },
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  theme: {
    colors: {
      primary: 'var(--accent-color)',
      secondary: 'var(--secondary-color)',
      accent: 'var(--accent-color)',
      muted: 'var(--text-muted)',
      background: 'var(--background-color)',
      surface: 'var(--surface-color)',
      text: 'var(--default-color)',
      heading: 'var(--heading-color)',
      border: 'var(--border-color)',
      card: 'var(--card-background)',
      cardBorder: 'var(--card-border)',
      code: 'var(--code-background)',
      tag: 'var(--tag-background)',
      tagText: 'var(--tag-text)',
      tagBorder: 'var(--tag-border)',
      input: 'var(--input-background)',
      inputBorder: 'var(--input-border)',
      inputText: 'var(--input-text)',
      nav: 'var(--nav-color)',
      navHover: 'var(--nav-hover-color)',
      navMobileBg: 'var(--nav-mobile-background)',
      navDropdownBg: 'var(--nav-dropdown-background)',
      navDropdown: 'var(--nav-dropdown-color)',
      navDropdownHover: 'var(--nav-dropdown-hover-color)',
      headerBg: 'var(--header-background-color)',
      headerColor: 'var(--header-color)',
    },
    fontFamily: {
      sans: 'var(--default-font)',
      heading: 'var(--heading-font)',
      nav: 'var(--nav-font)',
      mono: 'var(--monospace-font)',
    },
    fontSize: {
      base: 'var(--normal-font-size, 1rem)',
      sm: '0.875rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
      '7xl': '4.5rem',
      '8xl': '6rem',
      '9xl': '8rem',
    },
    spacing: {
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
    },
  },
});