// SPDX-FileCopyrightText: 2026 The freelance-persona_theme Project Contributors
//
// SPDX-License-Identifier: MIT

// uno.config.ts
import { defineConfig, presetUno, presetAttributify, presetIcons, transformerDirectives, transformerVariantGroup } from 'unocss';
import presetRemToPx from '@unocss/transformer-rem-to-px';

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({
      collections: {
        bi: () => import('@iconify-json/bi'),
        academicons: () => import('@iconify-json/academicons'),
      },
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
    presetRemToPx({ baseFontSize: 16 }),
  ],
  theme: {
    colors: {
      primary: 'var(--accent-color)',
      secondary: 'var(--secondary-color)',
      accent: 'var(--accent-color)',
      muted: 'var(--text-muted)',
      background: 'var(--background-color)',
      surface: 'var(--surface-color)',
      text: 'var(--default-color)',
      heading: 'var(--heading-color)',
      border: 'var(--border-color)',
      card: 'var(--card-background)',
      cardBorder: 'var(--card-border)',
      code: 'var(--code-background)',
      tag: 'var(--tag-background)',
      tagText: 'var(--tag-text)',
      tagBorder: 'var(--tag-border)',
      input: 'var(--input-background)',
      inputBorder: 'var(--input-border)',
      inputText: 'var(--input-text)',
      nav: 'var(--nav-color)',
      navHover: 'var(--nav-hover-color)',
      navMobileBg: 'var(--nav-mobile-background)',
      navDropdownBg: 'var(--nav-dropdown-background)',
      navDropdown: 'var(--nav-dropdown-color)',
      navDropdownHover: 'var(--nav-dropdown-hover-color)',
      headerBg: 'var(--header-background-color)',
      headerColor: 'var(--header-color)',
    },
    fontFamily: {
      sans: 'var(--default-font)',
      heading: 'var(--heading-font)',
      nav: 'var(--nav-font)',
      mono: 'var(--monospace-font)',
    },
    fontSize: {
      base: 'var(--normal-font-size, 1rem)',
      sm: '0.875rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
      '7xl': '4.5rem',
      '8xl': '6rem',
      '9xl': '8rem',
    },
    spacing: {
      '0': '0',
      '1': '0.25rem',
      '2': '0.5rem',
      '3': '0.75rem',
      '4': '1rem',
      '5': '1.25rem',
      '6': '1.5rem',
      '8': '2rem',
      '10': '2.5rem',
      '12': '3rem',
      '16': '4rem',
      '20': '5rem',
      '24': '6rem',
      '32': '8rem',
      '40': '10rem',
      '48': '12rem',
      '56': '14rem',
      '64': '16rem',
    },
    borderRadius: {
      none: '0',
      sm: '0.125rem',
      DEFAULT: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.75rem',
      '2xl': '1rem',
      '3xl': '1.5rem',
      full: '9999px',
    },
    boxShadow: {
      sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      DEFAULT: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
      md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
      xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
      inner: 'inset 0 2px 4px 0 rgb(0 0 0 / 0.05)',
      none: 'none',
    },
    transitionDuration: {
      '75': '75ms',
      '100': '100ms',
      '150': '150ms',
      '200': '200ms',
      '300': '300ms',
      '500': '500ms',
      '700': '700ms',
      '1000': '1000ms',
    },
    transitionTimingFunction: {
      DEFAULT: 'cubic-bezier(0.4, 0, 0.2, 1)',
      linear: 'linear',
      in: 'cubic-bezier(0.4, 0, 1, 1)',
      out: 'cubic-bezier(0, 0, 0.2, 1)',
      'in-out': 'cubic-bezier(0.4, 0, 0.2, 1)',
    },
  },
  shortcuts: {
    'container-main': 'mx-auto max-w-7xl px-4',
    'btn-primary': 'inline-flex items-center justify-center px-4 py-2 rounded bg-primary text-white hover:opacity-90 transition-colors duration-200 font-medium',
    'btn-secondary': 'inline-flex items-center justify-center px-4 py-2 rounded bg-surface border border-border text-text hover:bg-surface/80 transition-colors duration-200 font-medium',
    'btn-outline': 'inline-flex items-center justify-center px-4 py-2 rounded border-2 border-primary text-primary hover:bg-primary hover:text-white transition-colors duration-200 font-medium',
    'input-field': 'w-full px-3 py-2 rounded bg-input border border-input-border text-input-text placeholder:text-muted focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all duration-200',
    'card-base': 'bg-card border border-card-border rounded-lg shadow-sm',
    'link-primary': 'text-primary hover:underline transition-colors duration-150',
    'text-muted-sm': 'text-sm text-muted',
    'text-heading': 'font-heading text-heading font-semibold',
    'text-body': 'font-sans text-base',
    'flex-center': 'flex items-center justify-center',
    'flex-between': 'flex items-center justify-between',
    'flex-col': 'flex flex-col',
    'grid-cols-auto': 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4',
    'grid-cols-2': 'grid grid-cols-1 lg:grid-cols-2 gap-6',
    'grid-cols-3': 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6',
    'grid-cols-4': 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6',
  },
  safelist: [
    // Dynamic classes that may not be detected
    'open',
    'show',
    'active',
    'sr-only',
    'popover-open',
    // Icon classes
    /^i-bi:/,
    /^i-academicons:/,
    // Theme classes
    /theme-/,
    // Animation classes
    'revealed',
    'js-ready',
    'js-loading',
    'anim-init',
    // MathJax
    'mjx-',
    'MathJax',
  ],
});