name: Deploy Demo to Pages

on:
  push:
    branches:
      - main
    paths:
      - 'theme/**'
      - 'package.json'
      - 'bun.lock'
      - '.github/workflows/deploy-demo.yml'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
  SITE_URL: 'https://freelance-persona.github.io'
  BASE_PATH: '/astro-freelance-persona_theme'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bea81993200787e91129f1b95b8d00d # v4.2.2

      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install Dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Setup Playground
        run: bun run playground:setup

      - name: Build Demo Site
        run: bun run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@56afc603a1163273e04e2840552b759620ed7681 # v3.0.1
        with:
          path: ./playground/dist

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db9016c905b1b78297ea70c41d00b3f86b7722 # v4.0.5
