name: Deploy Demo to Pages

on:
  push:
    branches:
      - main
    paths:
      - 'theme/**'
      - 'package.json'
      - 'bun.lockb'
      - '.github/workflows/deploy-demo.yml'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Setup Playground
        run: bun run playground:setup

      - name: Build Demo Site
        run: bun run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./playground/dist

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
