name: Generate Baselines

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  generate:
    name: Generate Playwright Baselines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bea81993200787e91129f1b95b8d00d # v4.2.2

      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0

      - name: Install Dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Setup Playground
        run: bun run playground:setup

      - name: Install Playwright Browsers
        run: bunx playwright install chromium firefox --with-deps

      - name: Update Snapshots
        run: |
          cd playground
          bun run test --update-snapshots
          cp -r testing/tests/*-snapshots/ ../theme/starter/testing/tests/

      - name: Save Snapshots Cache
        uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            theme/starter/testing/tests/**/*-snapshots
          key: snapshots-${{ github.sha }}
