name: Renovate
on:
  workflow_dispatch:
  schedule:
    # Run daily at 03:27 UTC (using a non-zero minute to avoid top-of-the-hour GitHub Actions queue spikes)
    - cron: '27 3 * * *'

concurrency: renovate

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Host Egress Traffic
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Renovate Agent
        uses: renovatebot/github-action@693b9ef15eec82123529a37c782242f091365961 # v46.1.14
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN || secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
